import { baseStyles } from "../../styles";;
import { defineSlotRecipe } from "@pandacss/dev";

export const calendar = defineSlotRecipe({
  className: "calendar",
  slots: [
    "root",
    "clear-trigger",
    "content",
    "control",
    "input",
    "label",
    "month-select",
    "next-trigger",
    "positioner",
    "preset-trigger",
    "provider",
    "range-text",
    "table",
    "table-body",
    "table-head",
    "table-header",
    "table-row",
    "table-cell",
    "table-cell-trigger",
    "trigger",
    "view",
    "view-control",
    "view-trigger",
    "year-select",
    "context",
    "prev-trigger",
  ],

  base: {
    root: baseStyles.content,
    input: baseStyles.input,
    "clear-trigger": baseStyles.trigger,
    "preset-trigger": baseStyles.trigger,
    "table-cell-trigger": baseStyles.trigger,
    "view-trigger": baseStyles.trigger,
    "next-trigger": baseStyles.trigger,
    trigger: baseStyles.trigger,
    "prev-trigger": baseStyles.trigger,
    control: baseStyles.control,
    content: baseStyles.menu,
    context: baseStyles.content,
    "year-select": baseStyles.content,
    "month-select": baseStyles.content,
    table: {
      ...baseStyles.content,
      width: "full",
    },
    "table-body": baseStyles.content,
    "table-head": baseStyles.content,
    "table-header": {
      fontWeight: "400",
      fontSize: "1.4rem",
      color: "neutral.50",
    },
    "table-row": baseStyles.content,
    "table-cell": {
      ...baseStyles.content,
      textAlign: "center",
    },
    positioner: {
      ...baseStyles.content,
      width: "var(--reference-width)",
    },
    label: baseStyles.label,
    "range-text": baseStyles.text,
    view: baseStyles.content,
    "view-control": {
      ...baseStyles.content,
      width: "full",
      display: "inline-flex",
      alignItems: "center",
    },
  },
});
