import { defineSlotRecipe } from "@pandacss/dev";
import { baseStyles } from "../../styles";;

export const menu = defineSlotRecipe({
  className: "menu",
  slots: [
    "root",
    "item",
    "arrow",
    "trigger",
    "context",
    "content",
    "arrow-tip",
    "indicator",
    "item-text",
    "item-group",
    "positioner",
    "item-group",
    "radio-item",
    "separator",
    "trigger-item",
    "checkbox-item",
    "item-indicator",
    "context-trigger",
    "item-group-label",
    "radio-item-group",
  ],
  base: {
    arrow: baseStyles.arrow,
    positioner: {},
    "arrow-tip": baseStyles.arrowTip,
    root: baseStyles.content,
    content: baseStyles.menu,
    trigger: baseStyles.trigger,
    item: baseStyles.item,
    "item-group": baseStyles.content,
    separator: {},
    indicator: baseStyles.content,
    "item-text": baseStyles.text,
    "item-indicator": baseStyles.content,
    "item-group-label": baseStyles.label,
    "radio-item-group": baseStyles.content,
    "radio-item": baseStyles.content,
    "checkbox-item": baseStyles.content,
    "context-trigger": baseStyles.trigger,
    context: baseStyles.content,
    "trigger-item": baseStyles.content,
  },
});
